<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DATERP.Examination</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DATERP.Examination.Domain.Shared\DATERP.Examination.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.0.2" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.0.2" />
  </ItemGroup>

</Project>
