FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore DATERP.sln
WORKDIR /src/src/DATERP.DbMigrator
RUN dotnet publish -c Release -o /app/migrator

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/migrator .
ENTRYPOINT ["dotnet", "DATERP.DbMigrator.dll"]
